Add remaining course overview
UWindsorCSS/wiki pull request #143
Opened 2022-10-09 20:23 UTC by Lillliant

### What are you trying to accomplish?

Add the remaining course overview articles.

### How are you accomplishing it?

I wrote a python program that generated these articles based on the information in course.json and Jeremie's UWin API.

### Is there anything reviewers should know?

I think the sidebar is too cluttered with this many courses, so I put them into folders depending on whether they are CS courses and what year-level they're in.

### Checks before you create your pull request

-   [x] Did you read and follow article requirements?
-   [ ] Did you run prettier? I tried to format them like the previous articles so it probably will be fine
-   [x] Is it safe to rollback this change if anything goes wrong?

2022-10-09 20:38 UTC, jere-mie commented
Open data to the rescue 😎

2022-11-02 22:06 UTC, prairir requested changes
LGTM 🚀 🚀 . Please do that single change.

2022-11-02 22:06 UTC, prairir commented on courses/COMP-2067/Overview.md
> +This course introduces fundamental computer programming principles and structured programming concepts, with an emphasis on good programming. Stages of the software development cycles are introduced:
```suggestion
This course introduces fundamental computer programming principles and structured programming concepts, with an emphasis on good programming. Stages of the software development cycles are introduced: analysis, design, implementation, debugging and deployment. (May not be used to fulfill the major requirements of any major or joint major in Computer Science.) (3 lecture hours).

```

2022-11-13 02:50 UTC, prairir approved these changes
LGTM 🚀 🚀

2022-11-13 02:50 UTC, merged