Commit Details:
UWindsorCSS/wiki pull request #44
Opened 2022-02-15 00:19 UTC by nysdas

Added(1):
	setup.sh
	purgeCommands.sh
Modified(2):
	ReadME.md

Details:
1.
	- 'setup.sh' script will install all the dependencies for CSS Wiki App.
	- 'purgeCommands.sh` will purge all the dependencies we installed
	for the CSS Wiki

2.
	- Updated details how to run the script.

### Did you read and follow article requirements
Yes
### What are you trying to accomplish?
Updated the information: How to setup the initial environment.

### How are you accomplishing it?
Updating the README files

### Is there anything reviewers should know?
I have detailed information in the commit itself.

- [x] Is it safe to rollback this change if anything goes wrong?
- [ ] yes

2022-02-15 16:03 UTC, prairir requested changes

2022-02-15 16:03 UTC, prairir commented on setup.sh
> +#!/bin/bash
I dont think we should have a setup script. I think we should instead link to the official install resources.

Ubuntu is known for having out of date repos and I do not want to promote having out of date software.

2022-02-15 16:03 UTC, prairir commented on purgeCommands.sh
> +sudo apt-get purge cmdtest yarn -y
Same with `./setup.sh`

Also `cmdtest` and `yarn` are different in the apt repos. So this wouldnt purge yarn but get rid of an unrelated package

2022-02-15 16:03 UTC, prairir commented on README.md
> +```bash
I do not think we need to put the entire script in the readme

2022-02-15 16:03 UTC, prairir commented on README.md
> +```bash
same as above

2022-02-15 16:03 UTC, prairir commented on README.md
> +## Installation Steps for Ubuntu
I think its a good idea to list the dependencies above and link to the official installation guides.

I also think having a section entitled `Dependencies` and keep `Installation` the same.

2022-02-15 16:10 UTC, nysdas commented on README.md
> +```bash
I will remove the script Fromm Readme. just making sure You want to keep the setup.sh in the repo?

2022-02-15 16:12 UTC, nysdas commented on README.md
> +```bash
I didn't read your comment on the top that says you don't want script. Please ignore ^

2022-02-20 17:03 UTC, nysdas commented on setup.sh
> +#!/bin/bash
Setup.sh is removed.

2022-02-20 17:03 UTC, nysdas commented on purgeCommands.sh
> +sudo apt-get purge cmdtest yarn -y
removed

2022-02-20 17:04 UTC, nysdas commented on README.md
> +## Installation Steps for Ubuntu
Added dependencies in latest commit.

2022-02-20 17:10 UTC, kilbouri approved these changes
Looks fine to me.

2022-02-24 18:08 UTC, prairir commented
@nysdas looks good but please resolve the merge conflicts before merging

2022-02-24 18:08 UTC, prairir approved these changes

2022-02-24 18:53 UTC, closed without merging